/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplateNameRouteImport } from './routes/$templateName'
import { Route as IndexRouteImport } from './routes/index'

const TemplateNameRoute = TemplateNameRouteImport.update({
  id: '/$templateName',
  path: '/$templateName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$templateName': typeof TemplateNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$templateName': typeof TemplateNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$templateName': typeof TemplateNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$templateName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$templateName'
  id: '__root__' | '/' | '/$templateName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplateNameRoute: typeof TemplateNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$templateName': {
      id: '/$templateName'
      path: '/$templateName'
      fullPath: '/$templateName'
      preLoaderRoute: typeof TemplateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplateNameRoute: TemplateNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
