/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddonsFilenameRouteImport } from './routes/addons.$filename'
import { Route as TemplatesTemplateNameRouteImport } from './routes/templates.$templateName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsFilenameRoute = AddonsFilenameRouteImport.update({
  id: '/addons/$filename',
  path: '/addons/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateNameRoute = TemplatesTemplateNameRouteImport.update({
  id: '/templates/$templateName',
  path: '/templates/$templateName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addons/$filename': typeof AddonsFilenameRoute
  '/templates/$templateName': typeof TemplatesTemplateNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addons/$filename': typeof AddonsFilenameRoute
  '/templates/$templateName': typeof TemplatesTemplateNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addons/$filename': typeof AddonsFilenameRoute
  '/templates/$templateName': typeof TemplatesTemplateNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addons/$filename' | '/templates/$templateName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addons/$filename' | '/templates/$templateName'
  id: '__root__' | '/' | '/addons/$filename' | '/templates/$templateName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddonsFilenameRoute: typeof AddonsFilenameRoute
  TemplatesTemplateNameRoute: typeof TemplatesTemplateNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons/$filename': {
      id: '/addons/$filename'
      path: '/addons/$filename'
      fullPath: '/addons/$filename'
      preLoaderRoute: typeof AddonsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateName': {
      id: '/templates/$templateName'
      path: '/templates/$templateName'
      fullPath: '/templates/$templateName'
      preLoaderRoute: typeof TemplatesTemplateNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddonsFilenameRoute: AddonsFilenameRoute,
  TemplatesTemplateNameRoute: TemplatesTemplateNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
