# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: build
on: [push]
jobs:
  build-templates:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          # Add directories here when new templates are added
          - react
          - tss
          - tss-tw
          - tss-mantine
          - tss-shadcn
    defaults:
      run:
        working-directory: templates/${{ matrix.directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint project
        run: bun run lint --format=github
      - name: Build project
        run: bun run build

  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Lint project
        run: bun run lint --format=github
      - name: Build project
        run: bun run build
